name: Update License Annually

on:
  schedule:
    # Runs at midnight UTC on January 1 every year
    - cron: "0 0 1 1 *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run license generator
        run: node scripts/license.js -w LICENSE -f

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add LICENSE
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(license): auto-update license year $(date +'%Y')"
          git push
